services:
    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - '80:${FRONTEND_PORT}'
        depends_on:
            - backend

    backend:
        build: ./backend
        container_name: backend
        ports:
            - '${API_PORT}:${API_PORT}'
        env_file:
            - .env
