services:
    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - '80:${FRONTEND_PORT}'
        depends_on:
            - backend

    backend:
        build: ./backend
        container_name: backend
        ports:
            - '${API_PORT}:${API_PORT}'
        env_file:
            - .env
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        container_name: postgres_db
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data:
